[package]
name = "rust_todo"
version = "0.1.0"
authors = ["Jared Kerim <jkerim@mozilla.com>"]
edition = "2018"

[dependencies]
env_logger = "0.5"
dotenv = "0.9.0"
listenfd = "0.3"

actix = "0.7"
actix-web = "^0.7"

diesel = { version = "1.0.0", features = ["postgres"] }