version: '3.0'

services:
  api:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    command: systemfd --no-pid -s http::0.0.0.0:3000 -- cargo watch -x 'run --bin rust_todo'
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    links:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db/todo
  db:
    restart: always
    image: postgres:9.6
    volumes:
      - db_volume:/var/lib/postgresql

volumes:
  db_volume: